In [ ]:
# your name and student id
%cat /etc/hostname

ff01fdc1935e

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar05LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar05LC

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar05LC'

In [ ]:
%ls

first10rows.csv  last3rows.csv  Mar05LC_post.ipynb  Mar05LC_Pre.html  us-cities-top-1k.csv

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv("us-cities-top-1k.csv")
print(df1)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df2 = df1.head(10) # we get the top 10 rows
df2 # print(df2)

         City           State  Population        lat         lon
0  Marysville      Washington       63269  48.051764 -122.177082
1      Perris      California       72326  33.782519 -117.228648
2   Cleveland            Ohio      390113  41.499320  -81.694361
3   Worcester   Massachusetts      182544  42.262593  -71.802293
4    Columbia  South Carolina      133358  34.000710  -81.034814
5   Waterbury     Connecticut      109676  41.558153  -73.051496
6       Eagan       Minnesota       65453  44.804132  -93.166886
7  Southfield        Michigan       73006  42.473369  -83.221873
8   Lafayette       Louisiana      124276  30.224090  -92.019843
9  Boise City           Idaho      214237  43.618710 -116.214607

In [ ]:
df2.to_csv("first10rows.csv",index=False)

In [ ]:
%ls

first10rows.csv  Mar05LC_Pre.ipynb  us-cities-top-1k.csv

In [ ]:
df3 = df1.tail(3) # the last 3 rows
df3

          City           State  Population        lat         lon
997     Linden      New Jersey       41301  40.622048  -74.244590
998  Asheville  North Carolina       87236  35.595058  -82.551487
999    Compton      California       97877  33.895849 -118.220071

In [ ]:
df3.to_csv("last3rows.csv",index=True)

In [ ]:
%ls

first10rows.csv  last3rows.csv  Mar05LC_Pre.ipynb  us-cities-top-1k.csv

In [ ]:
%ls

first10rows.csv  last3rows.csv  Mar05LC_post.ipynb  Mar05LC_Pre.html  us-cities-top-1k.csv

In [ ]:
# pandas package, library, module
import pandas as pd
import os# operating system

In [ ]:
folder="folder1"

In [ ]:
if os.path.exists(folder):
  print(f"The path {folder} alreay exist.")
else:
  print(f"The path {folder} does not exist.")
  print("We are going to create it.")
  os.mkdir(folder)# make new folders
  print(f"A new folder {folder} is created.")

The path folder1 alreay exist.

In [ ]:
%ls

first10rows.csv  last3rows.csv       Mar05LC_Pre.html
folder1/         Mar05LC_post.ipynb  us-cities-top-1k.csv

In [ ]:
df1 = pd.read_csv('us-cities-top-1k.csv')
# data frame

In [ ]:
#
print(df1)
print(folder)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]
folder1

In [ ]:
df1# print(df1)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
print(folder)
print(folder)

folder1
folder1

In [ ]:
folder
folder #print(folder)

'folder1'

In [ ]:
# data frame
# series: only one row or one column
# short cut for print

df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df1.to_csv("1.csv",index=False)

In [ ]:
%ls

1.csv            folder1/       Mar05LC_post.ipynb  us-cities-top-1k.csv
first10rows.csv  last3rows.csv  Mar05LC_Pre.html

In [ ]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df1.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
# list
# warehouse, collection
# only get one column

# get multiple columns

In [ ]:
# only one column
s1 = df1['City'] # series
s1 # print(s1)

0         Marysville
1             Perris
2          Cleveland
3          Worcester
4           Columbia
           ...
995    West New York
996          Everett
997           Linden
998        Asheville
999          Compton
Name: City, Length: 1000, dtype: object

In [ ]:
s1.to_csv("2.csv",index=True)

In [ ]:
%ls

In [ ]:
# mutiple columns
df1.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
df2 = df1[ ['City', 'State'] ]# indexer
df2

              City           State
0       Marysville      Washington
1           Perris      California
2        Cleveland            Ohio
3        Worcester   Massachusetts
4         Columbia  South Carolina
..             ...             ...
995  West New York      New Jersey
996        Everett   Massachusetts
997         Linden      New Jersey
998      Asheville  North Carolina
999        Compton      California

[1000 rows x 2 columns]

In [ ]:
df2.to_csv("3.csv",index=False)

In [ ]:
%ls

1.csv  3.csv            folder1/       Mar05LC_post.ipynb  us-cities-top-1k.csv
2.csv  first10rows.csv  last3rows.csv  Mar05LC_Pre.html

In [ ]:
%%shell
jupyter nbconvert "Mar05LC_post.ipynb" --to html

[NbConvertApp] Converting notebook Mar05LC_post.ipynb to html
[NbConvertApp] Writing 376263 bytes to Mar05LC_post.html