In [ ]:
# your name and your student id
%cat /etc/hostname # print out your computer id

e2256e5c47ae

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar07LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar07LC

In [ ]:
%ls

Mar07LC_Pre.html  Mar07LC_Pre.ipynb  us-cities-top-1k.csv  UtahCities.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar07LC'

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv("us-cities-top-1k.csv")

In [ ]:
df1 # print(df1) shortcut

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
c1 = df1["State"]=="Utah" # condition
c1

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: State, Length: 1000, dtype: bool

In [ ]:
df2 = df1[c1]
df2

                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047

In [ ]:
df2.to_csv("UtahCities.csv",index=True)
# index=True save the row number
# index=False not saving the row number

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar07LC'

In [ ]:
%ls

Mar07LC_Post.ipynb  Mar07LC_Pre.html  us-cities-top-1k.csv  UtahCities.csv

In [ ]:
import pandas as pd# as alias

In [ ]:
df1 = pd.read_csv("us-cities-top-1k.csv")
print(df1)
# data frame
# series

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df1["City"]

0         Marysville
1             Perris
2          Cleveland
3          Worcester
4           Columbia
           ...
995    West New York
996          Everett
997           Linden
998        Asheville
999          Compton
Name: City, Length: 1000, dtype: object

In [ ]:
df2=df1[ ["City","Population"] ] # collection ["City","Pop"]
print(df2)
df2.to_csv("city_pop.csv",index=False)
# csv: comma

              City  Population
0       Marysville       63269
1           Perris       72326
2        Cleveland      390113
3        Worcester      182544
4         Columbia      133358
..             ...         ...
995  West New York       52122
996        Everett       42935
997         Linden       41301
998      Asheville       87236
999        Compton       97877

[1000 rows x 2 columns]

In [ ]:
%ls

city_pop.csv  Mar07LC_Post.ipynb  Mar07LC_Pre.html  us-cities-top-1k.csv  UtahCities.csv

In [ ]:
print(df1)# dataframe

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
s1 = df1.shape # collection
s1#

(1000, 5)

In [ ]:
print(s1[0])

1000

In [ ]:
len(df1)#print(len(df1))

1000

In [ ]:
cols = df1.columns
print(cols) # warehouse, collection

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
print(cols[1])

State

In [ ]:
# while:
# for:
l1 = [3,6, 10] #
for item in l1:
  print("repeat")
  print(item)

repeat
3
repeat
6
repeat
10

In [ ]:
df1.columns # collection

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
for c in df1.columns:
  print(c)
  s1 = df1[c]
  s1.to_csv(f"{c}.csv",index=False)

City
State
Population
lat
lon

In [ ]:
%ls

City.csv      lat.csv  Mar07LC_Post.ipynb  Population.csv  us-cities-top-1k.csv
city_pop.csv  lon.csv  Mar07LC_Pre.html    State.csv       UtahCities.csv

In [ ]:
print(df1)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
l2 = [2,3]
print(l2)

l3 = [2,3]*3
print(l3)

l4 = [3.14]*10
print(l4)

[2, 3]
[2, 3, 2, 3, 2, 3]
[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]

In [ ]:
print(df1)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df1["C1"]=[3.14]*1000 # series
print(df1)
print(df1.columns)
df1.to_csv("newPop.csv",index=False)

              City           State  Population        lat         lon    C1
0       Marysville      Washington       63269  48.051764 -122.177082  3.14
1           Perris      California       72326  33.782519 -117.228648  3.14
2        Cleveland            Ohio      390113  41.499320  -81.694361  3.14
3        Worcester   Massachusetts      182544  42.262593  -71.802293  3.14
4         Columbia  South Carolina      133358  34.000710  -81.034814  3.14
..             ...             ...         ...        ...         ...   ...
995  West New York      New Jersey       52122  40.787879  -74.014306  3.14
996        Everett   Massachusetts       42935  42.408430  -71.053663  3.14
997         Linden      New Jersey       41301  40.622048  -74.244590  3.14
998      Asheville  North Carolina       87236  35.595058  -82.551487  3.14
999        Compton      California       97877  33.895849 -118.220071  3.14

[1000 rows x 6 columns]
Index(['City', 'State', 'Population', 'lat', 'lon', 'C1'], dtype='object')

In [ ]:
%ls

City.csv      lat.csv  Mar07LC_Post.ipynb  newPop.csv      State.csv             UtahCities.csv
city_pop.csv  lon.csv  Mar07LC_Pre.html    Population.csv  us-cities-top-1k.csv

In [ ]:
print(df1)

              City           State  Population        lat         lon    C1
0       Marysville      Washington       63269  48.051764 -122.177082  3.14
1           Perris      California       72326  33.782519 -117.228648  3.14
2        Cleveland            Ohio      390113  41.499320  -81.694361  3.14
3        Worcester   Massachusetts      182544  42.262593  -71.802293  3.14
4         Columbia  South Carolina      133358  34.000710  -81.034814  3.14
..             ...             ...         ...        ...         ...   ...
995  West New York      New Jersey       52122  40.787879  -74.014306  3.14
996        Everett   Massachusetts       42935  42.408430  -71.053663  3.14
997         Linden      New Jersey       41301  40.622048  -74.244590  3.14
998      Asheville  North Carolina       87236  35.595058  -82.551487  3.14
999        Compton      California       97877  33.895849 -118.220071  3.14

[1000 rows x 6 columns]

In [ ]:
df1["C2"]=df1["City"]
df1#print(df1)

,City,State,Population,lat,lon,C1,C2
0,Marysville,Washington,63269,48.051764,-122.177082,3.14,Marysville
1,Perris,California,72326,33.782519,-117.228648,3.14,Perris
2,Cleveland,Ohio,390113,41.499320,-81.694361,3.14,Cleveland
3,Worcester,Massachusetts,182544,42.262593,-71.802293,3.14,Worcester
4,Columbia,South Carolina,133358,34.000710,-81.034814,3.14,Columbia
...,...,...,...,...,...,...,...
995,West New York,New Jersey,52122,40.787879,-74.014306,3.14,West New York
996,Everett,Massachusetts,42935,42.408430,-71.053663,3.14,Everett
997,Linden,New Jersey,41301,40.622048,-74.244590,3.14,Linden
998,Asheville,North Carolina,87236,35.595058,-82.551487,3.14,Asheville
999,Compton,California,97877,33.895849,-118.220071,3.14,Compton

In [ ]:
df1["NPop"]=df1["Population"]*1.1

In [ ]:
df1

,City,State,Population,lat,lon,C1,C2,NPop
0,Marysville,Washington,63269,48.051764,-122.177082,3.14,Marysville,69595.9
1,Perris,California,72326,33.782519,-117.228648,3.14,Perris,79558.6
2,Cleveland,Ohio,390113,41.499320,-81.694361,3.14,Cleveland,429124.3
3,Worcester,Massachusetts,182544,42.262593,-71.802293,3.14,Worcester,200798.4
4,Columbia,South Carolina,133358,34.000710,-81.034814,3.14,Columbia,146693.8
...,...,...,...,...,...,...,...,...
995,West New York,New Jersey,52122,40.787879,-74.014306,3.14,West New York,57334.2
996,Everett,Massachusetts,42935,42.408430,-71.053663,3.14,Everett,47228.5
997,Linden,New Jersey,41301,40.622048,-74.244590,3.14,Linden,45431.1
998,Asheville,North Carolina,87236,35.595058,-82.551487,3.14,Asheville,95959.6
999,Compton,California,97877,33.895849,-118.220071,3.14,Compton,107664.7

In [ ]:
df1.to_csv("newdata.csv",index=True)

In [ ]:
%ls

City.csv      lat.csv  Mar07LC_Post.ipynb  newdata.csv  Population.csv  us-cities-top-1k.csv
city_pop.csv  lon.csv  Mar07LC_Pre.html    newPop.csv   State.csv       UtahCities.csv

In [ ]:
%%shell
jupyter nbconvert "Mar07LC_Post.ipynb" --to html

[NbConvertApp] Converting notebook Mar07LC_Post.ipynb to html
[NbConvertApp] Writing 361689 bytes to Mar07LC_Post.html