In [ ]:
# your name and student id

%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar17LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar17LC

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar17LC'

In [ ]:
%ls

Mar17LC_pre.ipynb  us-cities-top-1k.csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("us-cities-top-1k.csv")
print(df) # df is dataframe

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
c1 = (df["State"]=="Utah") | (df["State"]=="Arizona") # | or
print(c1)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: State, Length: 1000, dtype: bool

In [ ]:
df1 = df[c1]
print(df1)
df1.to_csv("1.csv",index=False)

                 City    State  Population        lat         lon
31              Logan     Utah       48913  41.736980 -111.833836
99          Flagstaff  Arizona       68667  35.198284 -111.651302
108  Lake Havasu City  Arizona       52844  34.483901 -114.322455
112          Prescott  Arizona       40590  34.540024 -112.468502
122           Buckeye  Arizona       56683  33.370320 -112.583777
125        Scottsdale  Arizona      226918  33.494170 -111.926052
142           Gilbert  Arizona      229972  33.352826 -111.789027
149            Marana  Arizona       38290  32.436381 -111.222442
167            Tucson  Arizona      526116  32.221743 -110.926479
193      South Jordan     Utah       59366  40.562170 -111.929658
201        Oro Valley  Arizona       41627  32.390907 -110.966488
202              Mesa  Arizona      457587  33.415184 -111.831472
217          Maricopa  Arizona       45508  33.058106 -112.047642
235          Goodyear  Arizona       72864  33.435339 -112.357657
285         Bountiful     Utah       43023  40.889390 -111.880771
301      Sierra Vista  Arizona       45129  31.545500 -110.277286
381             Provo     Utah      116288  40.233844 -111.658534
394          Chandler  Arizona      249146  33.306160 -111.841250
401   Apache Junction  Arizona       37130  33.415048 -111.549578
418     Bullhead City  Arizona       39383  35.135939 -114.528598
434      Spanish Fork     Utah       36956  40.114955 -111.654923
437            Peoria  Arizona      162592  33.580596 -112.237378
438             Tempe  Arizona      168228  33.425510 -111.940005
440      Taylorsville     Utah       60519  40.667725 -111.938826
466          Riverton     Utah       40921  40.521893 -111.939102
480          Avondale  Arizona       78822  33.435598 -112.349602
500              Lehi     Utah       54382  40.391617 -111.850766
518       Casa Grande  Arizona       50111  32.879502 -111.757352
533             Ogden     Utah       84249  41.223000 -111.973830
568            Layton     Utah       70790  41.060222 -111.971053
574   Prescott Valley  Arizona       39791  34.610024 -112.315721
581          Surprise  Arizona      123546  33.629234 -112.367928
603            Murray     Utah       48612  40.666892 -111.887991
630             Sandy     Utah       90231  40.564978 -111.838973
673  West Valley City     Utah      133579  40.691613 -112.001050
676              Orem     Utah       91648  40.296898 -111.694648
737               Roy     Utah       37733  41.161611 -112.026331
762            Draper     Utah       45285  40.524671 -111.863823
778              Yuma  Arizona       91923  32.692651 -114.627692
856        St. George     Utah       76817  37.096528 -113.568416
955       West Jordan     Utah      110077  40.609670 -111.939103
964    Salt Lake City     Utah      191180  40.760779 -111.891047
966           Phoenix  Arizona     1513367  33.448377 -112.074037
980          Glendale  Arizona      234632  33.538652 -112.185987

In [ ]:
%ls

1.csv  Mar17LC_pre.ipynb  us-cities-top-1k.csv

In [ ]:
df2 = df[~c1]
print(df2)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[956 rows x 5 columns]

In [ ]:
df2.to_csv("2.csv",index=False)
%ls

1.csv  2.csv  Mar17LC_pre.ipynb  us-cities-top-1k.csv

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar17LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar17LC

In [ ]:
%ls

1.csv  2.csv  Mar17LC_pre.html  Mar17LC_pre.ipynb  us-cities-top-1k.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar17LC'

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("us-cities-top-1k.csv")
# dataframe
print(df)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
print(df.columns) # collection
#. Tom's microwave

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
s1 = df["Population"] # collection, series
print(s1)

0       63269
1       72326
2      390113
3      182544
4      133358
        ...
995     52122
996     42935
997     41301
998     87236
999     97877
Name: Population, Length: 1000, dtype: int64

In [ ]:
# max() min() mean()
max_v = s1.max()
print(max_v)

8405837

In [ ]:
#
print(df.columns) #print(df.columns)

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
s2 = df["State"] # indexer
print(s2)

0          Washington
1          California
2                Ohio
3       Massachusetts
4      South Carolina
            ...
995        New Jersey
996     Massachusetts
997        New Jersey
998    North Carolina
999        California
Name: State, Length: 1000, dtype: object

In [ ]:
# unique()
print(s2.unique())
states = s2.unique()
n = len(states)
print(n)

['Washington' 'California' 'Ohio' 'Massachusetts' 'South Carolina'
 'Connecticut' 'Minnesota' 'Michigan' 'Louisiana' 'Idaho' 'Indiana'
 'Georgia' 'Colorado' 'Florida' 'Illinois' 'Virginia' 'Texas' 'Kansas'
 'Mississippi' 'North Carolina' 'Missouri' 'New Mexico' 'Alabama' 'Utah'
 'Pennsylvania' 'New York' 'Wisconsin' 'Arkansas' 'Rhode Island' 'Iowa'
 'Nevada' 'Tennessee' 'Wyoming' 'Maryland' 'North Dakota' 'Oregon'
 'Arizona' 'Maine' 'Nebraska' 'New Jersey' 'Montana' 'Oklahoma'
 'West Virginia' 'South Dakota' 'District of Columbia' 'New Hampshire'
 'Alaska' 'Delaware' 'Kentucky' 'Hawaii' 'Vermont']
51

In [ ]:
df

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
s3 = df["State"]
r1 = s3.value_counts()
print(r1)

State
California              212
Texas                    83
Florida                  73
Illinois                 52
Massachusetts            36
Ohio                     33
Michigan                 31
Washington               28
Arizona                  25
Minnesota                24
New Jersey               22
North Carolina           22
Indiana                  21
Colorado                 21
Wisconsin                20
Utah                     19
Georgia                  18
Tennessee                17
New York                 17
Virginia                 17
Missouri                 16
Connecticut              15
Oregon                   14
Pennsylvania             13
Iowa                     13
Alabama                  12
South Carolina           12
Kansas                   11
Oklahoma                 11
Arkansas                 10
Louisiana                 9
Idaho                     8
New Mexico                7
Maryland                  7
Mississippi               6
Nevada                    6
Rhode Island              6
Kentucky                  5
North Dakota              4
Nebraska                  4
Montana                   4
New Hampshire             3
Wyoming                   2
West Virginia             2
South Dakota              2
Delaware                  2
Maine                     1
District of Columbia      1
Alaska                    1
Hawaii                    1
Vermont                   1
Name: count, dtype: int64

In [ ]:
# filtering
#head() tail()
df#print(df)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df.head(3)

         City       State  Population        lat         lon
0  Marysville  Washington       63269  48.051764 -122.177082
1      Perris  California       72326  33.782519 -117.228648
2   Cleveland        Ohio      390113  41.499320  -81.694361

In [ ]:
df.tail(2)

          City           State  Population        lat         lon
998  Asheville  North Carolina       87236  35.595058  -82.551487
999    Compton      California       97877  33.895849 -118.220071

In [ ]:
# list
l1=[False]*1000#
l1[0] = True
l1[1] = True
print(l1)

[True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

In [ ]:
df[l1] #

         City       State  Population        lat         lon
0  Marysville  Washington       63269  48.051764 -122.177082
1      Perris  California       72326  33.782519 -117.228648

In [ ]:
# & and | or ~ not
c1 = df["State"]=='Utah'
print(c1)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: State, Length: 1000, dtype: bool

In [ ]:
df[c1]

                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047

In [ ]:
df.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
c2 = df["Population"]>1000000
print(c2)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Population, Length: 1000, dtype: bool

In [ ]:
df[c2]

             City         State  Population        lat         lon
53   Philadelphia  Pennsylvania     1553165  39.952584  -75.165222
59         Dallas         Texas     1257676  32.776664  -96.796988
153   San Antonio         Texas     1409019  29.424122  -98.493628
333     San Diego    California     1355896  32.715738 -117.161084
594       Chicago      Illinois     2718782  41.878114  -87.629798
646       Houston         Texas     2195914  29.760427  -95.369803
890      New York      New York     8405837  40.712784  -74.005941
953   Los Angeles    California     3884307  34.052234 -118.243685
966       Phoenix       Arizona     1513367  33.448377 -112.074037

In [ ]:
df

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
%%shell
jupyter nbconvert "Mar17LC_post.ipynb" --to html

[NbConvertApp] Converting notebook Mar17LC_post.ipynb to html
[NbConvertApp] Writing 384085 bytes to Mar17LC_post.html