In [ ]:
# your name and student id

In [ ]:
%pip install jupysql duckdb duckdb-engine --quiet
# Load the SQL extension
%load_ext sql
# Setting: Show all rows
%config SqlMagic.displaylimit = None

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.3/95.3 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.8/192.8 kB 13.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 kB 5.3 MB/s eta 0:00:00

displaylimit: Value None will be treated as 0 (no limit)

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March26LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March26LC

In [ ]:
%ls

City.db  March26_LC_Pre.ipynb

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March26LC'

In [ ]:
# we connnecto the database file
%sql sqlite:///City.db

In [ ]:
%sqlcmd tables

+------+
| Name |
+------+
| data |
+------+

In [ ]:
%sqlcmd columns -t data

+------------+---------+----------+---------+-------------+
|    name    |   type  | nullable | default | primary_key |
+------------+---------+----------+---------+-------------+
|     ID     | INTEGER |  False   |   None  |      1      |
|    City    |   TEXT  |   True   |   None  |      0      |
|   State    |   TEXT  |   True   |   None  |      0      |
| Population | INTEGER |   True   |   None  |      0      |
|    lat     |   REAL  |   True   |   None  |      0      |
|    lon     |   REAL  |   True   |   None  |      0      |
+------------+---------+----------+---------+-------------+

In [ ]:
%%sql
select *
from data
where State='Utah'
order by Population desc
limit 10
;

Running query in 'sqlite:///City.db'

+-----+------------------+-------+------------+--------------------+---------------------+
|  ID |       City       | State | Population |        lat         |         lon         |
+-----+------------------+-------+------------+--------------------+---------------------+
| 965 |  Salt Lake City  |  Utah |   191180   |     40.7607793     | -111.89104740000002 |
| 674 | West Valley City |  Utah |   133579   | 40.691613200000006 |     -112.0010501    |
| 382 |      Provo       |  Utah |   116288   |     40.2338438     |     -111.6585337    |
| 956 |   West Jordan    |  Utah |   110077   |     40.6096698     |     -111.9391031    |
| 677 |       Orem       |  Utah |   91648    |     40.2968979     | -111.69464750000002 |
| 631 |      Sandy       |  Utah |   90231    | 40.564978100000005 |     -111.8389726    |
| 534 |      Ogden       |  Utah |   84249    |       41.223       |     -111.9738304    |
| 857 |    St. George    |  Utah |   76817    |     37.0965278     |     -113.5684164    |
| 569 |      Layton      |  Utah |   70790    |     41.0602216     |     -111.9710529    |
| 441 |   Taylorsville   |  Utah |   60519    |     40.6677248     |     -111.9388258    |
+-----+------------------+-------+------------+--------------------+---------------------+

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March26LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/March26LC

In [ ]:
%ls

City.db  March26_LC_Pre.html  March26_LC_Pre.ipynb  tips.csv

In [ ]:
import pandas as pd

In [ ]:
tips_df = pd.read_csv("tips.csv")
tips_df # print(tips_df)

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
# Task 6
c=tips_df['sex'].unique()
print(c)

['Female' 'Male']

In [ ]:
n = len(c)
print(n)

2

In [ ]:
gs = tips_df.groupby(by=["sex"]) #

In [ ]:
gs.groups.keys()

dict_keys(['Female', 'Male'])

In [ ]:
i='Female'
s_df = gs.get_group(i)
#s_df # print(s_df)

print(f"Sex: {i}")
#
d=s_df['size'].sum()
print(f"Total number of customers served: {d}")

#
d=s_df['total_bill'].sum()
print(f"Sum of total bill: ${d:.3f}")

#
d = len(s_df)
print(f"Total number of orders: {d}")

ss_df=s_df.sort_values(by=["total_bill","tip"],ascending=[False,False])
print(ss_df)

ss_df.to_csv(f"{i}_tips.csv",index=False)

Sex: Female
Total number of customers served: 214
Sum of total bill: $1570.950
Total number of orders: 87
      ID  total_bill   tip     sex smoker   day    time  size
102  103       44.30  2.50  Female    Yes   Sat  Dinner     3
197  198       43.11  5.00  Female    Yes  Thur   Lunch     4
238  239       35.83  4.67  Female     No   Sat  Dinner     3
11    12       35.26  5.00  Female     No   Sun  Dinner     4
85    86       34.83  5.17  Female     No  Thur   Lunch     4
..   ...         ...   ...     ...    ...   ...     ...   ...
135  136        8.51  1.25  Female     No  Thur   Lunch     2
145  146        8.35  1.50  Female     No  Thur   Lunch     2
111  112        7.25  1.00  Female     No   Sat  Dinner     1
92    93        5.75  1.00  Female    Yes   Fri  Dinner     2
67    68        3.07  1.00  Female    Yes   Sat  Dinner     1

[87 rows x 8 columns]

<ipython-input-20-0fd21653abcd>:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)

In [ ]:
gs = tips_df.groupby(by=['day'])
for i in gs.groups.keys():#["Male","Female"]:
  #i='Female'
  s_df = gs.get_group(i)
  #s_df # print(s_df)

  print(f"Sex: {i}")
  #
  d=s_df['size'].sum()
  print(f"Total number of customers served: {d}")

  #
  d=s_df['total_bill'].sum()
  print(f"Sum of total bill: ${d:.3f}")

  #
  d = len(s_df)
  print(f"Total number of orders: {d}")

  ss_df=s_df.sort_values(by=["total_bill","tip"],ascending=[False,False])
  print(ss_df)

  ss_df.to_csv(f"{i}_tips.csv",index=False)

Sex: Fri
Total number of customers served: 40
Sum of total bill: $325.880
Total number of orders: 19
      ID  total_bill   tip     sex smoker  day    time  size
95    96       40.17  4.73    Male    Yes  Fri  Dinner     4
90    91       28.97  3.00    Male    Yes  Fri  Dinner     2
96    97       27.28  4.00    Male    Yes  Fri  Dinner     2
94    95       22.75  3.25  Female     No  Fri  Dinner     2
91    92       22.49  3.50    Male     No  Fri  Dinner     2
98    99       21.01  3.00    Male    Yes  Fri  Dinner     2
93    94       16.32  4.30  Female    Yes  Fri  Dinner     2
225  226       16.27  2.50  Female    Yes  Fri   Lunch     2
223  224       15.98  3.00  Female     No  Fri   Lunch     3
101  102       15.38  3.00  Female    Yes  Fri  Dinner     2
221  222       13.42  3.48  Female    Yes  Fri   Lunch     2
224  225       13.42  1.58    Male    Yes  Fri   Lunch     2
99   100       12.46  1.50    Male     No  Fri  Dinner     2
220  221       12.16  2.20    Male    Yes  Fri   Lunch     2
97    98       12.03  1.50    Male    Yes  Fri  Dinner     2
100  101       11.35  2.50  Female    Yes  Fri  Dinner     2
226  227       10.09  2.00  Female    Yes  Fri   Lunch     2
222  223        8.58  1.92    Male    Yes  Fri   Lunch     1
92    93        5.75  1.00  Female    Yes  Fri  Dinner     2
Sex: Sat
Total number of customers served: 219
Sum of total bill: $1778.400
Total number of orders: 87
      ID  total_bill    tip     sex smoker  day    time  size
170  171       50.81  10.00    Male    Yes  Sat  Dinner     3
212  213       48.33   9.00    Male     No  Sat  Dinner     4
59    60       48.27   6.73    Male     No  Sat  Dinner     4
102  103       44.30   2.50  Female    Yes  Sat  Dinner     3
23    24       39.42   7.58    Male     No  Sat  Dinner     4
..   ...         ...    ...     ...    ...  ...     ...   ...
235  236       10.07   1.25    Male     No  Sat  Dinner     2
30    31        9.55   1.45    Male     No  Sat  Dinner     2
218  219        7.74   1.44    Male    Yes  Sat  Dinner     2
111  112        7.25   1.00  Female     No  Sat  Dinner     1
67    68        3.07   1.00  Female    Yes  Sat  Dinner     1

[87 rows x 8 columns]
Sex: Sun
Total number of customers served: 216
Sum of total bill: $1627.160
Total number of orders: 76
      ID  total_bill   tip     sex smoker  day    time  size
156  157       48.17  5.00    Male     No  Sun  Dinner     6
182  183       45.35  3.50    Male    Yes  Sun  Dinner     3
184  185       40.55  3.00    Male    Yes  Sun  Dinner     2
112  113       38.07  4.00    Male     No  Sun  Dinner     3
11    12       35.26  5.00  Female     No  Sun  Dinner     4
..   ...         ...   ...     ...    ...  ...     ...   ...
53    54        9.94  1.56    Male     No  Sun  Dinner     2
43    44        9.68  1.32    Male     No  Sun  Dinner     2
178  179        9.60  4.00  Female    Yes  Sun  Dinner     2
6      7        8.77  2.00    Male     No  Sun  Dinner     2
172  173        7.25  5.15    Male    Yes  Sun  Dinner     2

[76 rows x 8 columns]
Sex: Thur
Total number of customers served: 152
Sum of total bill: $1096.330
Total number of orders: 62
      ID  total_bill   tip     sex smoker   day   time  size
197  198       43.11  5.00  Female    Yes  Thur  Lunch     4
142  143       41.19  5.00    Male     No  Thur  Lunch     5
85    86       34.83  5.17  Female     No  Thur  Lunch     4
141  142       34.30  6.70    Male     No  Thur  Lunch     6
83    84       32.68  5.00    Male    Yes  Thur  Lunch     2
..   ...         ...   ...     ...    ...   ...    ...   ...
126  127        8.52  1.48    Male     No  Thur  Lunch     2
135  136        8.51  1.25  Female     No  Thur  Lunch     2
145  146        8.35  1.50  Female     No  Thur  Lunch     2
195  196        7.56  1.44    Male     No  Thur  Lunch     2
149  150        7.51  2.00    Male     No  Thur  Lunch     2

[62 rows x 8 columns]

<ipython-input-25-5905ff6b58ed>:4: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-25-5905ff6b58ed>:4: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-25-5905ff6b58ed>:4: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)
<ipython-input-25-5905ff6b58ed>:4: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  s_df = gs.get_group(i)

In [ ]:
# Task 9
c= (tips_df['sex']=='Female')&(tips_df['total_bill']>20)&(tips_df['tip']>5)

In [ ]:
s_df = tips_df[c]
s_df

      ID  total_bill   tip     sex smoker   day    time  size
52    53       34.81  5.20  Female     No   Sun  Dinner     4
85    86       34.83  5.17  Female     No  Thur   Lunch     4
155  156       29.85  5.14  Female     No   Sun  Dinner     5
214  215       28.17  6.50  Female    Yes   Sat  Dinner     3

In [ ]:
c = (tips_df['tip']>=5) & (tips_df['tip']<=10)
tips_df[c]

      ID  total_bill    tip     sex smoker   day    time  size
11    12       35.26   5.00  Female     No   Sun  Dinner     4
23    24       39.42   7.58    Male     No   Sat  Dinner     4
39    40       31.27   5.00    Male     No   Sat  Dinner     3
44    45       30.40   5.60    Male     No   Sun  Dinner     4
46    47       22.23   5.00    Male     No   Sun  Dinner     2
47    48       32.40   6.00    Male     No   Sun  Dinner     4
52    53       34.81   5.20  Female     No   Sun  Dinner     4
59    60       48.27   6.73    Male     No   Sat  Dinner     4
73    74       25.28   5.00  Female    Yes   Sat  Dinner     2
83    84       32.68   5.00    Male    Yes  Thur   Lunch     2
85    86       34.83   5.17  Female     No  Thur   Lunch     4
88    89       24.71   5.85    Male     No  Thur   Lunch     2
116  117       29.93   5.07    Male     No   Sun  Dinner     4
141  142       34.30   6.70    Male     No  Thur   Lunch     6
142  143       41.19   5.00    Male     No  Thur   Lunch     5
143  144       27.05   5.00  Female     No  Thur   Lunch     6
155  156       29.85   5.14  Female     No   Sun  Dinner     5
156  157       48.17   5.00    Male     No   Sun  Dinner     6
170  171       50.81  10.00    Male    Yes   Sat  Dinner     3
172  173        7.25   5.15    Male    Yes   Sun  Dinner     2
181  182       23.33   5.65    Male    Yes   Sun  Dinner     2
183  184       23.17   6.50    Male    Yes   Sun  Dinner     4
185  186       20.69   5.00    Male     No   Sun  Dinner     5
197  198       43.11   5.00  Female    Yes  Thur   Lunch     4
211  212       25.89   5.16    Male    Yes   Sat  Dinner     4
212  213       48.33   9.00    Male     No   Sat  Dinner     4
214  215       28.17   6.50  Female    Yes   Sat  Dinner     3
239  240       29.03   5.92    Male     No   Sat  Dinner     3

In [ ]:
tips_df['tip_ratio'] = tips_df['tip']/tips_df['total_bill']
tips_df

      ID  total_bill   tip     sex smoker   day    time  size  tip_ratio
0      1       16.99  1.01  Female     No   Sun  Dinner     2   0.059447
1      2       10.34  1.66    Male     No   Sun  Dinner     3   0.160542
2      3       21.01  3.50    Male     No   Sun  Dinner     3   0.166587
3      4       23.68  3.31    Male     No   Sun  Dinner     2   0.139780
4      5       24.59  3.61  Female     No   Sun  Dinner     4   0.146808
..   ...         ...   ...     ...    ...   ...     ...   ...        ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3   0.203927
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2   0.073584
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2   0.088222
242  243       17.82  1.75    Male     No   Sat  Dinner     2   0.098204
243  244       18.78  3.00  Female     No  Thur  Dinner     2   0.159744

[244 rows x 9 columns]

In [ ]:
%%shell
jupyter nbconvert "March26_LC_Post.ipynb" --to html

[NbConvertApp] Converting notebook March26_LC_Pre.ipynb to html
[NbConvertApp] Writing 283395 bytes to March26_LC_Pre.html