In [ ]:
# your name and student id
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar19LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar19LC

In [ ]:
%ls

March19_LC_Pre.ipynb  us-cities-top-1k.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar19LC'

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("us-cities-top-1k.csv")
print(df)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
print(df.columns)

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
df1 = df.sort_values(by=["Population"],ascending=[True]) # create a new dataframe, does not change
                                                   # original dataframe
print(df1)

             City         State  Population        lat         lon
961   Panama City       Florida       36877  30.158813  -85.660206
552        Beloit     Wisconsin       36888  42.508348  -89.031777
434  Spanish Fork          Utah       36956  40.114955 -111.654923
722        Keizer        Oregon       37064  44.990119 -123.026208
346       Weslaco         Texas       37093  26.159519  -97.990837
..            ...           ...         ...        ...         ...
53   Philadelphia  Pennsylvania     1553165  39.952584  -75.165222
646       Houston         Texas     2195914  29.760427  -95.369803
594       Chicago      Illinois     2718782  41.878114  -87.629798
953   Los Angeles    California     3884307  34.052234 -118.243685
890      New York      New York     8405837  40.712784  -74.005941

[1000 rows x 5 columns]

In [ ]:
df1.to_csv("sorted_data.csv",index=False)

In [ ]:
%ls

March19_LC_Pre.ipynb  sorted_data.csv  us-cities-top-1k.csv

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar19LC"

/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar19LC

In [ ]:
%pwd # print working directory

'/content/drive/MyDrive/Colab Notebooks/ANLY2500Spring2025/LC/Mar19LC'

In [ ]:
%ls # list

March19_LC_Post.ipynb  March19_LC_Pre.html  sorted_data.csv  us-cities-top-1k.csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("us-cities-top-1k.csv")
df# print(df) dataframe (table) collection

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
s1 = df['Population'] #indexer series
s1

0       63269
1       72326
2      390113
3      182544
4      133358
        ...
995     52122
996     42935
997     41301
998     87236
999     97877
Name: Population, Length: 1000, dtype: int64

In [ ]:
# max() min() mean() count() sum()
n=s1.sum()
# std()
n = s1.std()
print(n)

341690.1904632933

In [ ]:
# filtering
# ~ not
# & and
# | or
# c1 = ~(df["State"]=="Utah") #
#c1 = (df["State"]=="Utah") | (df["State"]=="Texas")  #
c1 = (df["State"]=="Utah") & (df["Population"]>50000) & (df["Population"]<80000)
c1

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
n_df = df[c1] # RAM
n=len(n_df)
print(n)
n_df

5

             City State  Population        lat         lon
193  South Jordan  Utah       59366  40.562170 -111.929658
440  Taylorsville  Utah       60519  40.667725 -111.938826
500          Lehi  Utah       54382  40.391617 -111.850766
568        Layton  Utah       70790  41.060222 -111.971053
856    St. George  Utah       76817  37.096528 -113.568416

In [ ]:
# sort_values()

In [ ]:
df.sort_values(by=["State","City"],ascending=[False,True])

            City      State  Population        lat         lon
258       Casper    Wyoming       59628  42.866632 -106.313081
64      Cheyenne    Wyoming       62448  41.139981 -104.820246
586     Appleton  Wisconsin       73596  44.261931  -88.415385
552       Beloit  Wisconsin       36888  42.508348  -89.031777
205   Brookfield  Wisconsin       37999  43.060567  -88.106479
..           ...        ...         ...        ...         ...
319      Madison    Alabama       45799  34.699258  -86.748332
388       Mobile    Alabama      194899  30.695366  -88.039891
30    Montgomery    Alabama      201332  32.366805  -86.299969
835  Phenix City    Alabama       37498  32.470976  -85.000765
412   Tuscaloosa    Alabama       95334  33.209841  -87.569174

[1000 rows x 5 columns]

In [ ]:
%%shell
jupyter nbconvert "March19_LC_Post.ipynb" --to html

[NbConvertApp] Converting notebook March19_LC_Post.ipynb to html
[NbConvertApp] Writing 325709 bytes to March19_LC_Post.html