**Put your name and student ID here**

# **Pandas**

*The `pandas` library provides high-performance, easy-to-use data structures and data analysis tools. The main data structure is the `DataFrame`, which you can think of as an in-memory 2D table (like a spreadsheet, with column names and row labels). Many features available in Excel are available programmatically, such as creating pivot tables, computing columns based on other columns, plotting graphs, etc. You can also group rows by column value, or join tables much like in SQL. Pandas is also great at handling time series.*

## Operator
<a href="https://docs.python.org/3/reference/expressions.html" target="_blank" style="font-weight:bold;font-size:20px;">Python 3 Operator Precedence Table (Ch.6.17)</a>
<table >
<thead>
<tr ><th ><p>Operator</p></th>
<th ><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr ><td><p><code ><span >(expressions...)</span></code>,</p>
<p><code ><span >[expressions...]</span></code>,
<code ><span >{key:</span> <span >value...}</span></code>,
<code ><span >{expressions...}</span></code></p>
</td>
<td><p>Binding or parenthesized
expression,
list display,
dictionary display,
set display</p></td>
</tr>
<tr ><td><p><code ><span >x[index]</span></code>, <code ><span >x[index:index]</span></code>,
<code ><span >x(arguments...)</span></code>, <code ><span >x.attribute</span></code></p></td>
<td><p>Subscription, slicing,
call, attribute reference</p></td>
</tr>
<tr ><td><p><a  href="#await"><code ><span >await</span> <span >x</span></code></a></p></td>
<td><p>Await expression</p></td>
</tr>
<tr ><td><p><code ><span >**</span></code></p></td>
<td><p>Exponentiation <a  href="#id21" id="id15">5</a></p></td>
</tr>
<tr ><td><p><code ><span >+x</span></code>, <code ><span >-x</span></code>, <code ><span >~x</span></code></p></td>
<td><p>Positive, negative, bitwise NOT</p></td>
</tr>
<tr ><td><p><code ><span >*</span></code>, <code ><span >@</span></code>, <code ><span >/</span></code>, <code ><span >//</span></code>, <code ><span >%</span></code></p></td>
<td><p>Multiplication, matrix
multiplication, division, floor
division, remainder <a  href="#id22" id="id16">6</a></p></td>
</tr>
<tr ><td><p><code ><span >+</span></code>, <code ><span >-</span></code></p></td>
<td><p>Addition and subtraction</p></td>
</tr>
<tr ><td><p><code ><span >&lt;&lt;</span></code>, <code ><span >&gt;&gt;</span></code></p></td>
<td><p>Shifts</p></td>
</tr>
<tr ><td><p><code ><span >&amp;</span></code></p></td>
<td><p>Bitwise AND</p></td>
</tr>
<tr ><td><p><code ><span >^</span></code></p></td>
<td><p>Bitwise XOR</p></td>
</tr>
<tr ><td><p><code ><span >|</span></code></p></td>
<td><p>Bitwise OR</p></td>
</tr>
<tr ><td><p><a  href="#in"><code ><span >in</span></code></a>, <a  href="#not-in"><code ><span >not</span> <span >in</span></code></a>,
<a  href="#is"><code ><span >is</span></code></a>, <a  href="#is-not"><code ><span >is</span> <span >not</span></code></a>, <code ><span >&lt;</span></code>,
<code ><span >&lt;=</span></code>, <code ><span >&gt;</span></code>, <code ><span >&gt;=</span></code>, <code ><span >!=</span></code>, <code ><span >==</span></code></p></td>
<td><p>Comparisons, including membership
tests and identity tests</p></td>
</tr>
<tr ><td><p><a  href="#not"><code ><span >not</span> <span >x</span></code></a></p></td>
<td><p>Boolean NOT</p></td>
</tr>
<tr ><td><p><a  href="#and"><code ><span >and</span></code></a></p></td>
<td><p>Boolean AND</p></td>
</tr>
<tr ><td><p><a  href="#or"><code ><span >or</span></code></a></p></td>
<td><p>Boolean OR</p></td>
</tr>
<tr ><td><p><a  href="#if-expr"><code ><span >if</span></code></a> – <code ><span >else</span></code></p></td>
<td><p>Conditional expression</p></td>
</tr>
<tr ><td><p><a  href="#lambda"><code ><span >lambda</span></code></a></p></td>
<td><p>Lambda expression</p></td>
</tr>
<tr ><td><p><code ><span >:=</span></code></p></td>
<td><p>Assignment expression</p></td>
</tr>
</tbody>
</table>

## Overview

In [ ]:
# us-cities-top-1k.csv
# Customers.csv
# Inventory.csv
# Sales.csv

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
%ls

Pandas_Notes_Finisher.ipynb  us-cities-top-1k.csv

In [6]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY6500Fall2024/LC/M2P1Pandas'

In [4]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY6500Fall2024/LC/M2P1Pandas"

/content/drive/MyDrive/Colab Notebooks/ANLY6500Fall2024/LC/M2P1Pandas

In [ ]:
#csv text file

In [7]:
import pandas as pd#

In [8]:
df1 = pd.read_csv("us-cities-top-1k.csv")

In [9]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
# data frame 2D vs series 1D

In [10]:
type(df1)

pandas.core.frame.DataFrame

In [11]:
df1.shape

(1000, 5)

In [12]:
df1.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [13]:
df1.index

RangeIndex(start=0, stop=1000, step=1)

In [14]:
df1.dtypes

City           object
State          object
Population      int64
lat           float64
lon           float64
dtype: object

In [17]:
df1.head(n=6)

         City           State  Population        lat         lon
0  Marysville      Washington       63269  48.051764 -122.177082
1      Perris      California       72326  33.782519 -117.228648
2   Cleveland            Ohio      390113  41.499320  -81.694361
3   Worcester   Massachusetts      182544  42.262593  -71.802293
4    Columbia  South Carolina      133358  34.000710  -81.034814
5   Waterbury     Connecticut      109676  41.558153  -73.051496

In [19]:
df1.tail(3)

          City           State  Population        lat         lon
997     Linden      New Jersey       41301  40.622048  -74.244590
998  Asheville  North Carolina       87236  35.595058  -82.551487
999    Compton      California       97877  33.895849 -118.220071

In [20]:
df1.describe()

         Population          lat          lon
count  1.000000e+03  1000.000000  1000.000000
mean   1.311324e+05    37.338241   -96.483023
std    3.416902e+05     5.279127    17.024468
min    3.687700e+04    21.306944  -157.858333
25%    4.969775e+04    33.748627  -116.959608
50%    6.820700e+04    37.768557   -93.238834
75%    1.098850e+05    41.618357   -82.171804
max    8.405837e+06    61.218056   -70.255326

In [21]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        1000 non-null   object
 1   State       1000 non-null   object
 2   Population  1000 non-null   int64
 3   lat         1000 non-null   float64
 4   lon         1000 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 39.2+ KB

### sort_values()

In [22]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [27]:
df2 = df1.sort_values(by=["Population","lat"],ascending=[False,False]) # create a new dataframe.
df2

             City         State  Population        lat         lon
890      New York      New York     8405837  40.712784  -74.005941
953   Los Angeles    California     3884307  34.052234 -118.243685
594       Chicago      Illinois     2718782  41.878114  -87.629798
646       Houston         Texas     2195914  29.760427  -95.369803
53   Philadelphia  Pennsylvania     1553165  39.952584  -75.165222
..            ...           ...         ...        ...         ...
346       Weslaco         Texas       37093  26.159519  -97.990837
722        Keizer        Oregon       37064  44.990119 -123.026208
434  Spanish Fork          Utah       36956  40.114955 -111.654923
552        Beloit     Wisconsin       36888  42.508348  -89.031777
961   Panama City       Florida       36877  30.158813  -85.660206

[1000 rows x 5 columns]

In [26]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

### indexing & filtering

In [32]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [29]:
df1.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [35]:
df3 = df1.set_index("City",drop=False)
df3

,City,State,Population,lat,lon
City,,,,,
Marysville,Marysville,Washington,63269,48.051764,-122.177082
Perris,Perris,California,72326,33.782519,-117.228648
Cleveland,Cleveland,Ohio,390113,41.499320,-81.694361
Worcester,Worcester,Massachusetts,182544,42.262593,-71.802293
Columbia,Columbia,South Carolina,133358,34.000710,-81.034814
...,...,...,...,...,...
West New York,West New York,New Jersey,52122,40.787879,-74.014306
Everett,Everett,Massachusetts,42935,42.408430,-71.053663
Linden,Linden,New Jersey,41301,40.622048,-74.244590
Asheville,Asheville,North Carolina,87236,35.595058,-82.551487
Compton,Compton,California,97877,33.895849,-118.220071

In [34]:
df3.columns

Index(['State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
# loc vs iloc
# location
# loc: string label
# iloc: integer label

In [36]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [37]:
df1.loc[1,"Population"]

72326

In [38]:
df1.iloc[1,2]

72326

In [39]:
df1.loc[[1,3],["City","Population"]]

        City  Population
1     Perris       72326
3  Worcester      182544

In [40]:
df1.loc[1:3,"City":"Population"]

        City          State  Population
1     Perris     California       72326
2  Cleveland           Ohio      390113
3  Worcester  Massachusetts      182544

In [41]:
df1.iloc[[1,3],[0,2]]

        City  Population
1     Perris       72326
3  Worcester      182544

In [43]:
df1.iloc[1:3+1,0:3]

        City          State  Population
1     Perris     California       72326
2  Cleveland           Ohio      390113
3  Worcester  Massachusetts      182544

In [44]:
df3

,City,State,Population,lat,lon
City,,,,,
Marysville,Marysville,Washington,63269,48.051764,-122.177082
Perris,Perris,California,72326,33.782519,-117.228648
Cleveland,Cleveland,Ohio,390113,41.499320,-81.694361
Worcester,Worcester,Massachusetts,182544,42.262593,-71.802293
Columbia,Columbia,South Carolina,133358,34.000710,-81.034814
...,...,...,...,...,...
West New York,West New York,New Jersey,52122,40.787879,-74.014306
Everett,Everett,Massachusetts,42935,42.408430,-71.053663
Linden,Linden,New Jersey,41301,40.622048,-74.244590
Asheville,Asheville,North Carolina,87236,35.595058,-82.551487
Compton,Compton,California,97877,33.895849,-118.220071

In [45]:
df3.iloc[1,2]

72326

In [46]:
df3.iloc[1:4,0:3]

                City          State  Population
City
Perris        Perris     California       72326
Cleveland  Cleveland           Ohio      390113
Worcester  Worcester  Massachusetts      182544

In [47]:
df3

,City,State,Population,lat,lon
City,,,,,
Marysville,Marysville,Washington,63269,48.051764,-122.177082
Perris,Perris,California,72326,33.782519,-117.228648
Cleveland,Cleveland,Ohio,390113,41.499320,-81.694361
Worcester,Worcester,Massachusetts,182544,42.262593,-71.802293
Columbia,Columbia,South Carolina,133358,34.000710,-81.034814
...,...,...,...,...,...
West New York,West New York,New Jersey,52122,40.787879,-74.014306
Everett,Everett,Massachusetts,42935,42.408430,-71.053663
Linden,Linden,New Jersey,41301,40.622048,-74.244590
Asheville,Asheville,North Carolina,87236,35.595058,-82.551487
Compton,Compton,California,97877,33.895849,-118.220071

In [48]:
df3.loc["Perris","Population"]

72326

In [50]:
df3.loc["Perris":"Worcester","City":"Population"]

                City          State  Population
City
Perris        Perris     California       72326
Cleveland  Cleveland           Ohio      390113
Worcester  Worcester  Massachusetts      182544

In [51]:
# filtering & get a few columns
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [52]:
df1["City"] # series 1D

0         Marysville
1             Perris
2          Cleveland
3          Worcester
4           Columbia
           ...
995    West New York
996          Everett
997           Linden
998        Asheville
999          Compton
Name: City, Length: 1000, dtype: object

In [53]:
type( df1["City"]  )

pandas.core.series.Series

In [56]:
df1[["City","Population"]] # DataFrame 2d

              City  Population
0       Marysville       63269
1           Perris       72326
2        Cleveland      390113
3        Worcester      182544
4         Columbia      133358
..             ...         ...
995  West New York       52122
996        Everett       42935
997         Linden       41301
998      Asheville       87236
999        Compton       97877

[1000 rows x 2 columns]

In [55]:
type(df1[["City"]] )

pandas.core.frame.DataFrame

In [57]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [60]:
r1 = df1["State"] =="Utah" # 1D Series
r1

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: State, Length: 1000, dtype: bool

In [68]:
r2 = (df1["Population"]>100000) & (df1["State"] =="Utah") & (df1["Population"]<150000)
r2

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [75]:
r3 = (df1["State"] == "Utah") | (df1["State"]=="Texas") # | or
r3

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: State, Length: 1000, dtype: bool

In [77]:
r4 = (df1["State"] == "Utah") | (df1["State"]=="Texas") # | or
r4

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: State, Length: 1000, dtype: bool

In [79]:
df1[~r4]

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[898 rows x 5 columns]

In [84]:
# max() min() mean() sum()
# value_counts()
df1["Population"].sum()

131132443

In [87]:
vc = df1["State"].value_counts() # only work on Series
vc

State
California              212
Texas                    83
Florida                  73
Illinois                 52
Massachusetts            36
Ohio                     33
Michigan                 31
Washington               28
Arizona                  25
Minnesota                24
New Jersey               22
North Carolina           22
Indiana                  21
Colorado                 21
Wisconsin                20
Utah                     19
Georgia                  18
Tennessee                17
New York                 17
Virginia                 17
Missouri                 16
Connecticut              15
Oregon                   14
Pennsylvania             13
Iowa                     13
Alabama                  12
South Carolina           12
Kansas                   11
Oklahoma                 11
Arkansas                 10
Louisiana                 9
Idaho                     8
New Mexico                7
Maryland                  7
Mississippi               6
Nevada                    6
Rhode Island              6
Kentucky                  5
North Dakota              4
Nebraska                  4
Montana                   4
New Hampshire             3
Wyoming                   2
West Virginia             2
South Dakota              2
Delaware                  2
Maine                     1
District of Columbia      1
Alaska                    1
Hawaii                    1
Vermont                   1
Name: count, dtype: int64

In [88]:
vc.index

Index(['California', 'Texas', 'Florida', 'Illinois', 'Massachusetts', 'Ohio',
       'Michigan', 'Washington', 'Arizona', 'Minnesota', 'New Jersey',
       'North Carolina', 'Indiana', 'Colorado', 'Wisconsin', 'Utah', 'Georgia',
       'Tennessee', 'New York', 'Virginia', 'Missouri', 'Connecticut',
       'Oregon', 'Pennsylvania', 'Iowa', 'Alabama', 'South Carolina', 'Kansas',
       'Oklahoma', 'Arkansas', 'Louisiana', 'Idaho', 'New Mexico', 'Maryland',
       'Mississippi', 'Nevada', 'Rhode Island', 'Kentucky', 'North Dakota',
       'Nebraska', 'Montana', 'New Hampshire', 'Wyoming', 'West Virginia',
       'South Dakota', 'Delaware', 'Maine', 'District of Columbia', 'Alaska',
       'Hawaii', 'Vermont'],
      dtype='object', name='State')

In [89]:
vc.values

array([212,  83,  73,  52,  36,  33,  31,  28,  25,  24,  22,  22,  21,
        21,  20,  19,  18,  17,  17,  17,  16,  15,  14,  13,  13,  12,
        12,  11,  11,  10,   9,   8,   7,   7,   6,   6,   6,   5,   4,
         4,   4,   3,   2,   2,   2,   2,   1,   1,   1,   1,   1])

### Groupby()

In [90]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [91]:
# grouby() divide the big dataframe into small ones
gps = df1.groupby(by=["State"])
gps

In [92]:
gps.groups.keys()

dict_keys(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'])

In [94]:
# get a group. get a dataframe
gps.get_group("Utah")

<ipython-input-94-e746b1690d79>:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  gps.get_group("Utah")

                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047

In [95]:
gps.count()

                      City  Population  lat  lon
State
Alabama                 12          12   12   12
Alaska                   1           1    1    1
Arizona                 25          25   25   25
Arkansas                10          10   10   10
California             212         212  212  212
Colorado                21          21   21   21
Connecticut             15          15   15   15
Delaware                 2           2    2    2
District of Columbia     1           1    1    1
Florida                 73          73   73   73
Georgia                 18          18   18   18
Hawaii                   1           1    1    1
Idaho                    8           8    8    8
Illinois                52          52   52   52
Indiana                 21          21   21   21
Iowa                    13          13   13   13
Kansas                  11          11   11   11
Kentucky                 5           5    5    5
Louisiana                9           9    9    9
Maine                    1           1    1    1
Maryland                 7           7    7    7
Massachusetts           36          36   36   36
Michigan                31          31   31   31
Minnesota               24          24   24   24
Mississippi              6           6    6    6
Missouri                16          16   16   16
Montana                  4           4    4    4
Nebraska                 4           4    4    4
Nevada                   6           6    6    6
New Hampshire            3           3    3    3
New Jersey              22          22   22   22
New Mexico               7           7    7    7
New York                17          17   17   17
North Carolina          22          22   22   22
North Dakota             4           4    4    4
Ohio                    33          33   33   33
Oklahoma                11          11   11   11
Oregon                  14          14   14   14
Pennsylvania            13          13   13   13
Rhode Island             6           6    6    6
South Carolina          12          12   12   12
South Dakota             2           2    2    2
Tennessee               17          17   17   17
Texas                   83          83   83   83
Utah                    19          19   19   19
Vermont                  1           1    1    1
Virginia                17          17   17   17
Washington              28          28   28   28
West Virginia            2           2    2    2
Wisconsin               20          20   20   20
Wyoming                  2           2    2    2

In [96]:
gps.sum()

,City,Population,lat,lon
State,,,,
Alabama,MontgomeryBirminghamHuntsvilleMadisonMobileTus...,1279813,398.337485,-1039.389966
Alaska,Anchorage,300950,61.218056,-149.900278
Arizona,FlagstaffLake Havasu CityPrescottBuckeyeScotts...,4691466,836.039978,-2804.145709
Arkansas,Fort SmithRogersNorth Little RockBentonvilleSp...,787011,355.015562,-930.718406
California,PerrisBuena ParkWestminsterRancho Palos Verdes...,27910620,7492.952668,-25280.881825
Colorado,ParkerLakewoodThorntonDenverLittletonPuebloCom...,3012284,834.131484,-2207.735259
Connecticut,WaterburyStamfordWest HavenHartfordNorwalkDanb...,1239817,621.158123,-1094.627139
Delaware,WilmingtonDover,108891,78.897240,-151.064156
District of Columbia,Washington,646449,38.907192,-77.036871
Florida,West Palm BeachDoralDaytona BeachNorth Lauderd...,7410114,1990.527355,-5918.796327
Georgia,MariettaColumbusSmyrnaAthens-Clarke CountyMaco...,1995615,599.259634,-1509.718979
Hawaii,Honolulu,347884,21.306944,-157.858333
Idaho,Boise CityCaldwellMeridianCoeur d'AleneNampaId...,638333,351.038079,-921.577778
Illinois,AuroraDeKalbNapervilleOak LawnSpringfieldCalum...,6055539,2162.165547,-4594.165071
Indiana,ElkhartBloomingtonFishersNoblesvilleLawrenceMi...,2393472,843.762206,-1812.048516
Iowa,UrbandaleCouncil BluffsWest Des MoinesWaterloo...,1037690,545.023755,-1209.739766
Kansas,Overland ParkLenexaLawrenceKansas CityManhatta...,1327215,426.755258,-1053.939388
Kentucky,CovingtonOwensboroLouisvilleLexington-FayetteB...,1079181,190.117349,-428.362698
Louisiana,LafayetteNew OrleansAlexandriaKennerShreveport...,1238263,279.715867,-828.737554
Maine,Portland,66318,43.661471,-70.255326
Maryland,GaithersburgFrederickAnnapolisBowieHagerstownR...,954852,274.559077,-539.368171
Massachusetts,WorcesterSalemWoburnFall RiverBostonWeymouth T...,3007084,1523.465414,-2568.990392
Michigan,SouthfieldSterling HeightsLincoln ParkFlintSt....,2979267,1320.702581,-2601.656673
Minnesota,EaganBurnsvilleBrooklyn ParkRochesterShakopeeM...,2055749,1080.930526,-2242.016601
Mississippi,JacksonSouthavenGulfportHattiesburgMeridianBiloxi,427944,191.742619,-536.169520
Missouri,Kansas CitySt. CharlesFlorissantSt. LouisCape ...,1843953,617.479079,-1477.262119
Montana,MissoulaBozemanBillingsGreat Falls,277392,185.833185,-444.823555
Nebraska,LincolnOmahaBellevueGrand Island,807304,164.158884,-386.939755
Nevada,HendersonRenoNorth Las VegasSparksCarson CityL...,1481832,226.636668,-704.572947
New Hampshire,NashuaManchesterConcord,239934,128.969143,-214.459927
New Jersey,TrentonAtlantic CityPassaicPatersonNewarkUnion...,1859793,891.781445,-1634.784157
New Mexico,RoswellAlbuquerqueRio RanchoClovisSanta FeLas ...,953296,242.852125,-741.916987
New York,BuffaloMount VernonSchenectadyBinghamtonAlbany...,9933332,712.116789,-1274.410096
North Carolina,GastoniaGreenvilleConcordChapel HillRaleighCar...,3358746,782.864963,-1748.999557
North Dakota,Grand ForksFargoMinotBismarck,281945,189.843737,-395.898688
Ohio,ClevelandLimaLancasterKetteringColumbusCuyahog...,3480839,1338.990692,-2730.964141
Oklahoma,TulsaOklahoma CityLawtonBroken ArrowMuskogeeSt...,1666530,392.209544,-1067.810012
Oregon,PortlandSalemTigardEugeneBeavertonHillsboroLak...,1680656,626.502145,-1719.071319
Pennsylvania,AllentownPhiladelphiaLancasterErieHarrisburgSt...,2598080,528.333068,-999.752100
Rhode Island,East ProvidenceWoonsocketCranstonWarwickPawtuc...,499878,250.999211,-428.533675
South Carolina,ColumbiaMount PleasantGreenvilleSpartanburgFlo...,812734,403.522873,-967.185113
South Dakota,Rapid CitySioux Falls,235488,87.625139,-199.962118
Tennessee,KingsportFranklinBartlettNashvilleCollierville...,2483464,607.908888,-1474.555429
Texas,LubbockRowlettNorth Richland HillsDallasTexark...,14836230,2592.202092,-8068.718125
Utah,LoganSouth JordanBountifulProvoSpanish ForkTay...,1440569,769.775435,-2127.342681
Vermont,Burlington,42284,44.475882,-73.212072
Virginia,LeesburgBlacksburgLynchburgCharlottesvilleNewp...,2236964,637.343800,-1320.011487
Washington,MarysvilleSpokaneKennewickBellinghamLakewoodBu...,2956938,1325.057098,-3404.782064
West Virginia,HuntingtonCharleston,99998,76.769069,-164.077777
Wisconsin,New BerlinLa CrosseWest AllisWaukeshaWausauFon...,1910367,868.591663,-1772.943430
Wyoming,CheyenneCasper,122076,84.006613,-211.133327

In [98]:
df4 = gps.get_group("Utah")
df4

<ipython-input-98-fe3f685ca85c>:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df4 = gps.get_group("Utah")

                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047

In [99]:
df4.to_csv("UtahCities1.csv",index=True)
df4.to_csv("UtahCities2.csv",index=False)

In [107]:
# add columns#
df1

,City,State,Population,lat,lon,NC1,NC2
0,Marysville,Washington,63269,48.051764,-122.177082,100,65167.07
1,Perris,California,72326,33.782519,-117.228648,100,74495.78
2,Cleveland,Ohio,390113,41.499320,-81.694361,100,401816.39
3,Worcester,Massachusetts,182544,42.262593,-71.802293,100,188020.32
4,Columbia,South Carolina,133358,34.000710,-81.034814,100,137358.74
...,...,...,...,...,...,...,...
996,Everett,Massachusetts,42935,42.408430,-71.053663,100,44223.05
997,Linden,New Jersey,41301,40.622048,-74.244590,100,42540.03
998,Asheville,North Carolina,87236,35.595058,-82.551487,100,89853.08
999,Compton,California,97877,33.895849,-118.220071,100,100813.31
1000,New City,New State,100000,0.000000,0.000000,0,0.00

In [102]:
df1["NC1"]=[100]*1000

In [104]:
df1["NC2"]=df1["Population"]*1.03

In [ ]:
# delete columns delete rows

In [106]:
df1.loc[1000]=["New City","New State",100000,0,0,0,0]

In [109]:
df1.drop(["NC1","NC2"],axis=1) # delete columns

            City           State  Population        lat         lon
0     Marysville      Washington       63269  48.051764 -122.177082
1         Perris      California       72326  33.782519 -117.228648
2      Cleveland            Ohio      390113  41.499320  -81.694361
3      Worcester   Massachusetts      182544  42.262593  -71.802293
4       Columbia  South Carolina      133358  34.000710  -81.034814
...          ...             ...         ...        ...         ...
996      Everett   Massachusetts       42935  42.408430  -71.053663
997       Linden      New Jersey       41301  40.622048  -74.244590
998    Asheville  North Carolina       87236  35.595058  -82.551487
999      Compton      California       97877  33.895849 -118.220071
1000    New City       New State      100000   0.000000    0.000000

[1001 rows x 5 columns]

In [110]:
df1.drop([0,2],axis=0) # delete rows

,City,State,Population,lat,lon,NC1,NC2
1,Perris,California,72326,33.782519,-117.228648,100,74495.78
3,Worcester,Massachusetts,182544,42.262593,-71.802293,100,188020.32
4,Columbia,South Carolina,133358,34.000710,-81.034814,100,137358.74
5,Waterbury,Connecticut,109676,41.558153,-73.051496,100,112966.28
6,Eagan,Minnesota,65453,44.804132,-93.166886,100,67416.59
...,...,...,...,...,...,...,...
996,Everett,Massachusetts,42935,42.408430,-71.053663,100,44223.05
997,Linden,New Jersey,41301,40.622048,-74.244590,100,42540.03
998,Asheville,North Carolina,87236,35.595058,-82.551487,100,89853.08
999,Compton,California,97877,33.895849,-118.220071,100,100813.31
1000,New City,New State,100000,0.000000,0.000000,0,0.00

In [111]:
df1

,City,State,Population,lat,lon,NC1,NC2
0,Marysville,Washington,63269,48.051764,-122.177082,100,65167.07
1,Perris,California,72326,33.782519,-117.228648,100,74495.78
2,Cleveland,Ohio,390113,41.499320,-81.694361,100,401816.39
3,Worcester,Massachusetts,182544,42.262593,-71.802293,100,188020.32
4,Columbia,South Carolina,133358,34.000710,-81.034814,100,137358.74
...,...,...,...,...,...,...,...
996,Everett,Massachusetts,42935,42.408430,-71.053663,100,44223.05
997,Linden,New Jersey,41301,40.622048,-74.244590,100,42540.03
998,Asheville,North Carolina,87236,35.595058,-82.551487,100,89853.08
999,Compton,California,97877,33.895849,-118.220071,100,100813.31
1000,New City,New State,100000,0.000000,0.000000,0,0.00

### Operator ~

### Series value_counts() function

### apply() function

regular expression search() function
<a href="https://docs.python.org/3/library/re.html#re.search">https://docs.python.org/3/library/re.html#re.search</a>

## Operator
<a href="https://docs.python.org/3/reference/expressions.html" target="_blank" style="font-weight:bold;font-size:20px;">Python 3 Operator Precedence Table (Ch.6.17)</a>
<table >
<thead>
<tr ><th ><p>Operator</p></th>
<th ><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr ><td><p><code ><span >(expressions...)</span></code>,</p>
<p><code ><span >[expressions...]</span></code>,
<code ><span >{key:</span> <span >value...}</span></code>,
<code ><span >{expressions...}</span></code></p>
</td>
<td><p>Binding or parenthesized
expression,
list display,
dictionary display,
set display</p></td>
</tr>
<tr ><td><p><code ><span >x[index]</span></code>, <code ><span >x[index:index]</span></code>,
<code ><span >x(arguments...)</span></code>, <code ><span >x.attribute</span></code></p></td>
<td><p>Subscription, slicing,
call, attribute reference</p></td>
</tr>
<tr ><td><p><a  href="#await"><code ><span >await</span> <span >x</span></code></a></p></td>
<td><p>Await expression</p></td>
</tr>
<tr ><td><p><code ><span >**</span></code></p></td>
<td><p>Exponentiation <a  href="#id21" id="id15">5</a></p></td>
</tr>
<tr ><td><p><code ><span >+x</span></code>, <code ><span >-x</span></code>, <code ><span >~x</span></code></p></td>
<td><p>Positive, negative, bitwise NOT</p></td>
</tr>
<tr ><td><p><code ><span >*</span></code>, <code ><span >@</span></code>, <code ><span >/</span></code>, <code ><span >//</span></code>, <code ><span >%</span></code></p></td>
<td><p>Multiplication, matrix
multiplication, division, floor
division, remainder <a  href="#id22" id="id16">6</a></p></td>
</tr>
<tr ><td><p><code ><span >+</span></code>, <code ><span >-</span></code></p></td>
<td><p>Addition and subtraction</p></td>
</tr>
<tr ><td><p><code ><span >&lt;&lt;</span></code>, <code ><span >&gt;&gt;</span></code></p></td>
<td><p>Shifts</p></td>
</tr>
<tr ><td><p><code ><span >&amp;</span></code></p></td>
<td><p>Bitwise AND</p></td>
</tr>
<tr ><td><p><code ><span >^</span></code></p></td>
<td><p>Bitwise XOR</p></td>
</tr>
<tr ><td><p><code ><span >|</span></code></p></td>
<td><p>Bitwise OR</p></td>
</tr>
<tr ><td><p><a  href="#in"><code ><span >in</span></code></a>, <a  href="#not-in"><code ><span >not</span> <span >in</span></code></a>,
<a  href="#is"><code ><span >is</span></code></a>, <a  href="#is-not"><code ><span >is</span> <span >not</span></code></a>, <code ><span >&lt;</span></code>,
<code ><span >&lt;=</span></code>, <code ><span >&gt;</span></code>, <code ><span >&gt;=</span></code>, <code ><span >!=</span></code>, <code ><span >==</span></code></p></td>
<td><p>Comparisons, including membership
tests and identity tests</p></td>
</tr>
<tr ><td><p><a  href="#not"><code ><span >not</span> <span >x</span></code></a></p></td>
<td><p>Boolean NOT</p></td>
</tr>
<tr ><td><p><a  href="#and"><code ><span >and</span></code></a></p></td>
<td><p>Boolean AND</p></td>
</tr>
<tr ><td><p><a  href="#or"><code ><span >or</span></code></a></p></td>
<td><p>Boolean OR</p></td>
</tr>
<tr ><td><p><a  href="#if-expr"><code ><span >if</span></code></a> – <code ><span >else</span></code></p></td>
<td><p>Conditional expression</p></td>
</tr>
<tr ><td><p><a  href="#lambda"><code ><span >lambda</span></code></a></p></td>
<td><p>Lambda expression</p></td>
</tr>
<tr ><td><p><code ><span >:=</span></code></p></td>
<td><p>Assignment expression</p></td>
</tr>
</tbody>
</table>

### add one row
df.loc["index"]=["name","n",123,0]

### delete row(s)
df.drop(["index1","index2"],axis=0)

# Setup

First, let's import `pandas`. People usually import it as `pd`:

# `Series` objects
The `pandas` library contains the following useful data structures:
* `Series` objects, that we will discuss now. A `Series` object is 1D array, similar to a column in a spreadsheet (with a column name and row labels).
* `DataFrame` objects. This is a 2D table, similar to a spreadsheet (with column names and row labels).
* `Panel` objects. You can see a `Panel` as a dictionary of `DataFrame`s. These are less used, so we will not discuss them here.

## Creating a `Series`
Let's start by creating our first `Series` object!
s=pd.Series(data=[23,34,56,],index=["aiden","tom","kelly"],name="age")

## Similar to a 1D `ndarray`
`Series` objects behave much like one-dimensional NumPy `ndarray`s, and you can often pass them as parameters to NumPy functions:

Arithmetic operations on `Series` are also possible, and they apply *elementwise*, just like for `ndarray`s:

Similar to NumPy, if you add a single number to a `Series`, that number is added to all items in the `Series`. This is called * broadcasting*:

The same is true for all binary operations such as `*` or `/`, and even conditional operations:

## Index labels
Each item in a `Series` object has a unique identifier called the *index label*. By default, it is simply the rank of the item in the `Series` (starting from `0`) but you can also set the index labels manually:

You can then use the `Series` just like a `dict`:

You can still access the items by integer location, like in a regular array:

To make it clear when you are accessing by label or by integer location, it is recommended to always use the `loc` attribute when accessing by label, and the `iloc` attribute when accessing by integer location:

Slicing a `Series` also slices the index labels:

This can lead to unexpected results when using the default numeric labels, so be careful:

Oh, look! The first element has index label `2`. The element with index label `0` is absent from the slice:

But remember that you can access elements by integer location using the `iloc` attribute. This illustrates another reason why it's always better to use `loc` and `iloc` to access `Series` objects:

## Init from `dict`
You can create a `Series` object from a `dict`. The keys will be used as index labels:

You can control which elements you want to include in the `Series` and in what order by explicitly specifying the desired `index`:

## Automatic alignment
When an operation involves multiple `Series` objects, `pandas` automatically aligns items by matching index labels.

The resulting `Series` contains the union of index labels from `s2` and `s3`. Since `"colin"` is missing from `s2` and `"charles"` is missing from `s3`, these items have a `NaN` result value (i.e. Not-a-Number means *missing*).

Automatic alignment is very handy when working with data that may come from various sources with varying structure and missing items. But if you forget to set the right index labels, you can have surprising results:

Pandas could not align the `Series`, since their labels do not match at all, hence the full `NaN` result.

## Init with a scalar
You can also initialize a `Series` object using a scalar and a list of index labels: all items will be set to the scalar.

## `Series` name
A `Series` can have a `name`:

# `DataFrame` objects
A DataFrame object represents a spreadsheet, with cell values, column names and row index labels. You can define expressions to compute columns based on other columns, create pivot-tables, group rows, draw graphs, etc. You can see `DataFrame`s as dictionaries of `Series`.

## Creating a `DataFrame`
You can create a DataFrame by passing a dictionary of `Series` objects:

In [ ]:
import pandas as pd
people_dict = {
    "weight": pd.Series([68, 83, 112], index=["alice", "bob", "charles"]),
    "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"], name="year"),
    "children": pd.Series([0, 3], index=["charles", "bob"]),
    "hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),
    "grade":pd.Series(data=[96.6,86.6,76.6],index=["bob", "alice", "charles"],name="g")
}
people = pd.DataFrame(people_dict)
people

         weight  birthyear  children    hobby  grade
alice        68       1985       NaN   Biking   86.6
bob          83       1984       3.0  Dancing   96.6
charles     112       1992       0.0      NaN   76.6

A few things to note:
* the `Series` were automatically aligned based on their index,
* missing values are represented as `NaN`,
* `Series` names are ignored (the name `"year"` was dropped),
* `DataFrame`s are displayed nicely in Jupyter notebooks, woohoo!

You can access columns pretty much as you would expect. They are returned as `Series` objects:

You can also get multiple columns at once:

If you pass a list of columns and/or index row labels to the `DataFrame` constructor, it will guarantee that these columns and/or rows will exist, in that order, and no other column/row will exist. For example:

Another convenient way to create a `DataFrame` is to pass all the values to the constructor as an `ndarray`, or a list of lists, and specify the column names and row index labels separately:

Instead of an `ndarray`, you can also pass a `DataFrame` object:

It is also possible to create a `DataFrame` with a dictionary (or list) of dictionaries (or lists):

## Transposing
You can swap columns and indices using the `T` attribute:

## Most methods return modified copies
As you may have noticed, the `stack()` and `unstack()` methods do not modify the object they are called on. Instead, they work on a copy and return that copy. This is true of most methods in pandas.

## Accessing rows
Let's go back to the `people` `DataFrame`:

The `loc` attribute lets you access rows instead of columns. The result is a `Series` object in which the `DataFrame`'s column names are mapped to row index labels:

You can also access rows by integer location using the `iloc` attribute:

You can also get a slice of rows, and this returns a `DataFrame` object:

Finally, you can pass a boolean array to get the matching rows:

This is most useful when combined with boolean expressions:

## Adding and removing columns
You can generally treat `DataFrame` objects like dictionaries of `Series`, so the following works fine:

When you add a new column, it must have the same number of rows. Missing rows are filled with NaN, and extra rows are ignored:

When adding a new column, it is added at the end (on the right) by default. You can also insert a column anywhere else using the `insert()` method:

## Assigning new columns
You can also create new columns by calling the `assign()` method. Note that this returns a new `DataFrame` object, the original is not modified:

Note that you cannot access columns created within the same assignment:

The solution is to split this assignment in two consecutive assignments:

Having to create a temporary variable `d6` is not very convenient. You may want to just chain the assignment calls, but it does not work because the `people` object is not actually modified by the first assignment:

But fear not, there is a simple solution. You can pass a function to the `assign()` method (typically a `lambda` function), and this function will be called with the `DataFrame` as a parameter:

Problem solved!

## Evaluating an expression
A great feature supported by pandas is expression evaluation. It relies on the `numexpr` library which must be installed.

Assignment expressions are also supported. Let's set `inplace=True` to directly modify the `DataFrame` rather than getting a modified copy:

You can use a local or global variable in an expression by prefixing it with `'@'`:

## Querying a `DataFrame`
The `query()` method lets you filter a `DataFrame` based on a query expression:

## Sorting a `DataFrame`
You can sort a `DataFrame` by calling its `sort_index` method. By default, it sorts the rows by their index label, in ascending order, but let's reverse the order:

Note that `sort_index` returned a sorted *copy* of the `DataFrame`. To modify `people` directly, we can set the `inplace` argument to `True`. Also, we can sort the columns instead of the rows by setting `axis=1`:

To sort the `DataFrame` by the values instead of the labels, we can use `sort_values` and specify the column to sort by:

## Operations on `DataFrame`s
Although `DataFrame`s do not try to mimic NumPy arrays, there are a few similarities. Let's create a `DataFrame` to demonstrate this:

In [ ]:
import pandas as pd
import numpy as np
grades_array = np.array([[8, 8, 9], [10, 9, 9], [4, 8, 2], [9, 10, 10]])
grades = pd.DataFrame(grades_array, columns=["sep", "oct", "nov"], index=["alice", "bob", "charles", "darwin"])
grades

         sep  oct  nov
alice      8    8    9
bob       10    9    9
charles    4    8    2
darwin     9   10   10

You can apply NumPy mathematical functions on a `DataFrame`: the function is applied to all values:

Similarly, adding a single value to a `DataFrame` will add that value to all elements in the `DataFrame`. This is called *broadcasting*:

Of course, the same is true for all other binary operations, including arithmetic (`*`,`/`,`**`...) and conditional (`>`, `==`...) operations:

Aggregation operations, such as computing the `max`, the `sum` or the `mean` of a `DataFrame`, apply to each column, and you get back a `Series` object:

The `all` method is also an aggregation operation: it checks whether all values are `True` or not. Let's see during which months all students got a grade greater than `5`:

Most of these functions take an optional `axis` parameter which lets you specify along which axis of the `DataFrame` you want the operation executed. The default is `axis=0`, meaning that the operation is executed vertically (on each column). You can set `axis=1` to execute the operation horizontally (on each row). For example, let's find out which students had all grades greater than `5`:

The `any` method returns `True` if any value is True. Let's see who got at least one grade 10:

If you add a `Series` object to a `DataFrame` (or execute any other binary operation), pandas attempts to broadcast the operation to all *rows* in the `DataFrame`. This only works if the `Series` has the same size as the `DataFrame`s rows. For example, let's subtract the `mean` of the `DataFrame` (a `Series` object) from the `DataFrame`:

We subtracted `7.75` from all September grades, `8.75` from October grades and `7.50` from November grades. It is equivalent to subtracting this `DataFrame`:

If you want to subtract the global mean from every grade, here is one way to do it:

## Automatic alignment
Similar to `Series`, when operating on multiple `DataFrame`s, pandas automatically aligns them by row index label, but also by column names. Let's create a `DataFrame` with bonus points for each person from October to December:

In [ ]:
import pandas as pd
import numpy as np
grades_array = np.array([[8, 8, 9], [10, 9, 9], [4, 8, 2], [9, 10, 10]])
grades = pd.DataFrame(grades_array, columns=["sep", "oct", "nov"], index=["alice", "bob", "charles", "darwin"])
grades

         sep  oct  nov
alice      8    8    9
bob       10    9    9
charles    4    8    2
darwin     9   10   10

In [ ]:
bonus_array = np.array([[0, np.nan, 2], [np.nan, 1, 0], [0, 1, 0], [3, 3, 0]])
bonus_points = pd.DataFrame(bonus_array, columns=["oct", "nov", "dec"], index=["bob", "colin", "darwin", "charles"])
bonus_points

         oct  nov  dec
bob      0.0  NaN  2.0
colin    NaN  1.0  0.0
darwin   0.0  1.0  0.0
charles  3.0  3.0  0.0

Looks like the addition worked in some cases but way too many elements are now empty. That's because when aligning the `DataFrame`s, some columns and rows were only present on one side, and thus they were considered missing on the other side (`NaN`). Then adding `NaN` to a number results in `NaN`, hence the result.

## Handling missing data
Dealing with missing data is a frequent task when working with real life data. Pandas offers a few tools to handle missing data.

Let's try to fix the problem above. For example, we can decide that missing data should result in a zero, instead of `NaN`. We can replace all `NaN` values by any value using the `fillna()` method:

In [ ]:
import pandas as pd
import numpy as np
grades_array = np.array([[8, 8, 9], [10, 9, 9], [4, 8, 2], [9, 10, 10]])
grades = pd.DataFrame(grades_array, columns=["sep", "oct", "nov"], index=["alice", "bob", "charles", "darwin"])
grades

         sep  oct  nov
alice      8    8    9
bob       10    9    9
charles    4    8    2
darwin     9   10   10

In [ ]:
bonus_array = np.array([[0, np.nan, 2], [np.nan, 1, 0], [0, 1, 0], [3, 3, 0]])
bonus_points = pd.DataFrame(bonus_array, columns=["oct", "nov", "dec"], index=["bob", "colin", "darwin", "charles"])
bonus_points

         oct  nov  dec
bob      0.0  NaN  2.0
colin    NaN  1.0  0.0
darwin   0.0  1.0  0.0
charles  3.0  3.0  0.0

In [ ]:
m_df=grades+bonus_points
m_df

         dec   nov   oct  sep
alice    NaN   NaN   NaN  NaN
bob      NaN   NaN   9.0  NaN
charles  NaN   5.0  11.0  NaN
colin    NaN   NaN   NaN  NaN
darwin   NaN  11.0  10.0  NaN

It's a bit unfair that we're setting grades to zero in September, though. Perhaps we should decide that missing grades are missing grades, but missing bonus points should be replaced by zeros:

That's much better: although we made up some data, we have not been too unfair.

Another way to handle missing data is to interpolate. Let's look at the `bonus_points` `DataFrame` again:

Now let's call the `interpolate` method. By default, it interpolates vertically (`axis=0`), so let's tell it to interpolate horizontally (`axis=1`).

Bob had 0 bonus points in October, and 2 in December. When we interpolate for November, we get the mean: 1 bonus point. Colin had 1 bonus point in November, but we do not know how many bonus points he had in September, so we cannot interpolate, this is why there is still a missing value in October after interpolation. To fix this, we can set the September bonus points to 0 before interpolation.

Great, now we have reasonable bonus points everywhere. Let's find out the final grades:

It is slightly annoying that the September column ends up on the right. This is because the `DataFrame`s we are adding do not have the exact same columns (the `grades` `DataFrame` is missing the `"dec"` column), so to make things predictable, pandas orders the final columns alphabetically. To fix this, we can simply add the missing column before adding:

There's not much we can do about December and Colin: it's bad enough that we are making up bonus points, but we can't reasonably make up grades (well, I guess some teachers probably do). So let's call the `dropna()` method to get rid of rows that are full of `NaN`s:

Now let's remove columns that are full of `NaN`s by setting the `axis` argument to `1`:

## Aggregating with `groupby`
Similar to the SQL language, pandas allows grouping your data into groups to run calculations over each group.

First, let's add some extra data about each person so we can group them, and let's go back to the `final_grades` `DataFrame` so we can see how `NaN` values are handled:

Now let's group data in this `DataFrame` by hobby:

We are ready to compute the average grade per hobby:

That was easy! Note that the `NaN` values have simply been skipped when computing the means.

## Overview functions
When dealing with large `DataFrames`, it is useful to get a quick overview of its content. Pandas offers a few functions for this. First, let's create a large `DataFrame` with a mix of numeric values, missing values and text values. Notice how Jupyter displays only the corners of the `DataFrame`:

The `head()` method returns the top 5 rows:

Of course, there's also a `tail()` function to view the bottom 5 rows. You can pass the number of rows you want:

The `info()` method prints out a summary of each column's contents:

Finally, the `describe()` method gives a nice overview of the main aggregated values over each column:
* `count`: number of non-null (not NaN) values
* `mean`: mean of non-null values
* `std`: [standard deviation](https://en.wikipedia.org/wiki/Standard_deviation) of non-null values
* `min`: minimum of non-null values
* `25%`, `50%`, `75%`: 25th, 50th and 75th [percentile](https://en.wikipedia.org/wiki/Percentile) of non-null values
* `max`: maximum of non-null values

# Saving & loading
Pandas can save `DataFrame`s to various backends, including file formats such as CSV, Excel, JSON, HTML and HDF5, or to a SQL database. Let's create a `DataFrame` to demonstrate this:

In [ ]:
import numpy as np
import pandas as pd
my_df = pd.DataFrame(
    data=[["Biking", 68.5, 1985, np.nan], ["Dancing", 83.1, 1984, 3]],
    columns=["hobby", "weight", "birthyear", "children"],
    index=["alice", "bob"]
)
my_df

         hobby  weight  birthyear  children
alice   Biking    68.5       1985       NaN
bob    Dancing    83.1       1984       3.0

## Saving
Let's save it to CSV, HTML and JSON:
my_df.to_csv("my_df.csv")
my_df.to_html("my_df.html")
my_df.to_json("my_df.json")

## Loading
Now let's load our CSV file back into a `DataFrame`:
my_df_loaded = pd.read_csv("my_df.csv", index_col=0)

As you might guess, there are similar `read_json`, `read_html`, `read_excel` functions as well.  We can also read data straight from the Internet. For example, let's load the top 1,000 U.S. cities:

There are more options available, in particular regarding datetime format. Check out the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) for more details.

# Combining `DataFrame`s

## SQL-like joins
One powerful feature of pandas is its ability to perform SQL-like joins on `DataFrame`s. Various types of joins are supported: inner joins, left/right outer joins and full joins. To illustrate this, let's start by creating a couple of simple `DataFrame`s:

In [ ]:
city_loc = pd.DataFrame(
    [
        ["CA", "San Francisco", 37.781334, -122.416728],
        ["NY", "New York", 40.705649, -74.008344],
        ["FL", "Miami", 25.791100, -80.320733],
        ["OH", "Cleveland", 41.473508, -81.739791],
        ["UT", "Salt Lake City", 40.755851, -111.896657]
    ], columns=["state", "city", "lat", "lng"])
city_loc

  state            city        lat         lng
0    CA   San Francisco  37.781334 -122.416728
1    NY        New York  40.705649  -74.008344
2    FL           Miami  25.791100  -80.320733
3    OH       Cleveland  41.473508  -81.739791
4    UT  Salt Lake City  40.755851 -111.896657

In [ ]:
city_pop = pd.DataFrame(
    [
        [808976, "San Francisco", "California"],
        [8363710, "New York", "New-York"],
        [413201, "Miami", "Florida"],
        [2242193, "Houston", "Texas"]
    ], index=[3,4,5,6], columns=["population", "city", "state"])
city_pop

   population           city       state
3      808976  San Francisco  California
4     8363710       New York    New-York
5      413201          Miami     Florida
6     2242193        Houston       Texas

Now let's join these `DataFrame`s using the `merge()` function:

Note that both `DataFrame`s have a column named `state`, so in the result they got renamed to `state_x` and `state_y`.

Also, note that Cleveland, Salt Lake City and Houston were dropped because they don't exist in *both* `DataFrame`s. This is the equivalent of a SQL `INNER JOIN`. If you want a `FULL OUTER JOIN`, where no city gets dropped and `NaN` values are added, you must specify `how="outer"`:

Of course, `LEFT OUTER JOIN` is also available by setting `how="left"`: only the cities present in the left `DataFrame` end up in the result. Similarly, with `how="right"` only cities in the right `DataFrame` appear in the result. For example:

If the key to join on is actually in one (or both) `DataFrame`'s index, you must use `left_index=True` and/or `right_index=True`. If the key column names differ, you must use `left_on` and `right_on`. For example:

## Concatenation
Rather than joining `DataFrame`s, we may just want to concatenate them. That's what `concat()` is for:

In [ ]:
city_pop = pd.DataFrame(
    [
        [808976, "San Francisco", "California"],
        [8363710, "New York", "New-York"],
        [413201, "Miami", "Florida"],
        [2242193, "Houston", "Texas"]
    ], index=[3,4,5,6], columns=["population", "city", "state"])
city_pop

   population           city       state
3      808976  San Francisco  California
4     8363710       New York    New-York
5      413201          Miami     Florida
6     2242193        Houston       Texas

In [ ]:
city_loc = pd.DataFrame(
    [
        ["CA", "San Francisco", 37.781334, -122.416728],
        ["NY", "New York", 40.705649, -74.008344],
        ["FL", "Miami", 25.791100, -80.320733],
        ["OH", "Cleveland", 41.473508, -81.739791],
        ["UT", "Salt Lake City", 40.755851, -111.896657]
    ], columns=["state", "city", "lat", "lng"])
city_loc

  state            city        lat         lng
0    CA   San Francisco  37.781334 -122.416728
1    NY        New York  40.705649  -74.008344
2    FL           Miami  25.791100  -80.320733
3    OH       Cleveland  41.473508  -81.739791
4    UT  Salt Lake City  40.755851 -111.896657

Note that this operation aligned the data horizontally (by columns) but not vertically (by rows). In this example, we end up with multiple rows having the same index (e.g. 3). Pandas handles this rather gracefully:

Or you can tell pandas to just ignore the index:

Notice that when a column does not exist in a `DataFrame`, it acts as if it was filled with `NaN` values. If we set `join="inner"`, then only columns that exist in *both* `DataFrame`s are returned:

You can concatenate `DataFrame`s horizontally instead of vertically by setting `axis=1`:

In this case it really does not make much sense because the indices do not align well (e.g. Cleveland and San Francisco end up on the same row, because they shared the index label `3`). So let's reindex the `DataFrame`s by city name before concatenating:

This looks a lot like a `FULL OUTER JOIN`, except that the `state` columns were not renamed to `state_x` and `state_y`, and the `city` column is now the index.